url: .

paths:
  logo: images/logo.png

exclude:
    - Makefile
    - cssinline.py
    - tmp
    - Gemfile

mini_magick:
    thumbnail:
        source: images/original
        destination: images/thumbnail
        resize: "100x100"
    medium:
        source: images/original
        destination: images/medium
        resize: "640x480"
    newsletter:
        source: images/original
        destination: images/newsletter
        resize: "580x"

gems: [jekyll-minimagick]
